replicaCount: 2
image:
  repository: ghcr.io/ulan08/helloweb3
  tag: v
nameOverride: bcw-test
fullnameOverride: bcw-test
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
envs:
  - name: PORT
    value: '3000'
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: gce
  hosts:
    - host: bcw-test.local
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
