name: deployment
on: 
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat ./package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: |
          echo 'VERSION=${{ fromJson(env.PACKAGE_JSON).version }} >>${GITHUB_ENV}'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: downcase repository name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:v${{ env.VERSION }}
      - name: Update Image Version in the values file
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm/helloWeb3/values.yaml'
          propertyPath: 'image.tag'
          value: v${{ env.VERSION }}
          createPR: false
          branch: release
          message: 'Update Image Version to ${{ steps.image.outputs.version }}'
          masterBranchName: main